// src/lib/constants/branches.ts

export const INDIAN_COLLEGE_BRANCHES = [
  "CSE",
  "CSE (AI & ML)",
  "CSE (Data Science)",
  "CSE (Cyber Security)",
  "CSE (IoT)",
  "CSE (Cloud Computing)",
  "CSE (Blockchain)",
  "CSE (Business Systems)",
  "CSE (AI)",
  "CSE (Gaming Technology)",
  "IT",
  "AI & DS",
  "AI & ML",
  "Artificial Intelligence",
  "Data Science",
  "Cyber Security",
  "Information Security",
  "Software Engineering",
  "ECE",
  "EEE",
  "Electrical Engineering",
  "Electrical & Electronics Engineering",
  "Electronics Engineering",
  "Electronics & Communication Engineering",
  "Electronics & Instrumentation Engineering",
  "Instrumentation Engineering",
  "Instrumentation & Control Engineering",
  "VLSI Design",
  "Embedded Systems",
  "Communication Engineering",
  "Mechanical Engineering",
  "Automobile Engineering",
  "Automotive Engineering",
  "Manufacturing Engineering",
  "Production Engineering",
  "Industrial Engineering",
  "Robotics Engineering",
  "Mechatronics",
  "Tool Engineering",
  "Thermal Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Construction Engineering",
  "Transportation Engineering",
  "Environmental Engineering",
  "Geo Informatics",
  "Geotechnical Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Petrochemical Engineering",
  "Oil & Gas Engineering",
  "AERO",
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Aircraft Maintenance Engineering",
  "Avionics",
  "BIOTECH",
  "Biotechnology",
  "Biomedical Engineering",
  "Bioinformatics",
  "Genetic Engineering",
  "Biochemical Engineering",
  "Mining Engineering",
  "Metallurgical Engineering",
  "Metallurgy",
  "Marine Engineering",
  "Naval Architecture",
  "Ceramic Engineering",
  "Textile Engineering",
  "Food Technology",
  "Agricultural Engineering",
  "Dairy Technology",
  "Plastic Engineering",
  "Leather Technology",
  "Printing Technology",
  "B.Arch",
  "Architecture",
  "Planning",
  "Interior Design",
  "Urban Planning",
  "BCA",
  "MCA",
  "Computer Applications",
  "B.Sc",
  "B.Sc Computer Science",
  "B.Sc IT",
  "B.Sc Data Science",
  "B.Sc AI",
  "B.Sc Mathematics",
  "B.Sc Physics",
  "B.Sc Chemistry",
  "B.Sc Biotechnology",
  "B.Sc Statistics",
  "B.Sc Electronics",
  "B.Sc Agriculture",
  "B.Sc Nursing",
  "B.Sc Psychology",
  "B.Sc Nutrition",
  "B.Sc Animation",
  "B.Sc Multimedia",
  "B.Com",
  "B.Com General",
  "B.Com Computers",
  "B.Com Honours",
  "B.Com Taxation",
  "B.Com Accounting & Finance",
  "BBA",
  "BBM",
  "MBA",
  "PGDM",
  "Business Administration",
  "Business Analytics",
  "Finance",
  "Marketing",
  "HR",
  "Operations",
  "Hospital Management",
  "Hotel Management",
  "Event Management",
  "Retail Management",
  "BA",
  "BA English",
  "BA Economics",
  "BA Political Science",
  "BA History",
  "BA Sociology",
  "BA Psychology",
  "BA Journalism",
  "BA Mass Communication",
  "Public Administration",
  "Law",
  "LLB",
  "BA LLB",
  "BBA LLB",
  "LLM",
  "MBBS",
  "BDS",
  "BAMS",
  "BHMS",
  "BUMS",
  "BPT",
  "Pharmacy",
  "B.Pharm",
  "M.Pharm",
  "Pharm D",
  "Nursing",
  "Medical Lab Technology",
  "Radiology",
  "Optometry",
  "Agriculture",
  "Horticulture",
  "Forestry",
  "Veterinary Science",
  "Fisheries Science",
  "Fashion Design",
  "Graphic Design",
  "Animation",
  "Multimedia",
  "Fine Arts",
  "Performing Arts",
  "Diploma",
  "Polytechnic",
  "Education",
  "B.Ed",
  "M.Ed",
  "M.Tech",
  "M.Sc",
  "MA",
  "PhD"
] as const;