export const INDIAN_COLLEGE_BRANCHES = [
  "CSE",
  "CSE (AI & ML)",
  "CSE (Data Science)",
  "CSE (Cyber Security)",
  "CSE (IoT)",
  "CSE (Cloud Computing)",
  "CSE (Blockchain)",
  "CSE (Business Systems)",
  "CSE (AI)",
  "CSE (Gaming Technology)",
  "IT",
  "AI & DS",
  "AI & ML",
  "Artificial Intelligence",
  "Data Science",
  "Cyber Security",
  "Information Security",
  "Software Engineering",
  "ECE",
  "EEE",
  "Electrical Engineering",
  "Electrical & Electronics Engineering",
  "Electronics Engineering",
  "Electronics & Communication Engineering",
  "Electronics & Instrumentation Engineering",
  "Instrumentation Engineering",
  "Instrumentation & Control Engineering",
  "VLSI Design",
  "Embedded Systems",
  "Communication Engineering",
  "Mechanical Engineering",
  "Automobile Engineering",
  "Automotive Engineering",
  "Manufacturing Engineering",
  "Production Engineering",
  "Industrial Engineering",
  "Robotics Engineering",
  "Mechatronics",
  "Tool Engineering",
  "Thermal Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Construction Engineering",
  "Transportation Engineering",
  "Environmental Engineering",
  "Geo Informatics",
  "Geotechnical Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Petrochemical Engineering",
  "Oil & Gas Engineering",
  "AERO",
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Aircraft Maintenance Engineering",
  "Avionics",
  "BIOTECH",
  "Biotechnology",
  "Biomedical Engineering",
  "Bioinformatics",
  "Genetic Engineering",
  "Biochemical Engineering",
  "Mining Engineering",
  "Metallurgical Engineering",
  "Metallurgy",
  "Marine Engineering",
  "Naval Architecture",
  "Textile Engineering",
  "Textile Technology",
  "Food Technology",
  "Agricultural Engineering",
  "BBA",
  "MBA",
  "B.Com",
  "M.Com",
  "BCA",
  "MCA",
  "B.Sc",
  "M.Sc",
  "BA",
  "MA",
  "Other"
] as const;

export type CollegeBranch = typeof INDIAN_COLLEGE_BRANCHES[number];