// src/lib/constants/branches.ts

export const INDIAN_COLLEGE_BRANCHES = [
  // Computer Science & Information Technology
  "CSE (Computer Science & Engineering)",
  "CSE (AI & ML)",
  "CSE (Data Science)",
  "CSE (Cyber Security)",
  "CSE (IoT & Automation)",
  "CSE (Cloud Computing)",
  "CSE (Blockchain Technology)",
  "CSE (Business Systems)",
  "CSE (Gaming Technology)",
  "IT (Information Technology)",
  "Artificial Intelligence & Data Science",
  "Artificial Intelligence & Machine Learning",
  "Cyber Security & Information Assurance",
  "Software Engineering",

  // Electronics & Electrical Streams
  "ECE (Electronics & Communication Engineering)",
  "EEE (Electrical & Electronics Engineering)",
  "Electronics & Instrumentation Engineering",
  "Instrumentation & Control Engineering",
  "VLSI Design & Embedded Systems",
  "Communication Engineering",

  // Core Engineering Streams
  "Mechanical Engineering",
  "Automobile / Automotive Engineering",
  "Mechatronics Engineering",
  "Robotics & Automation",
  "Manufacturing & Industrial Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Environmental Engineering",
  "Chemical Engineering",
  "Petroleum & Petrochemical Engineering",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Aircraft Maintenance Engineering",
  "Avionics",
  "Biotechnology",
  "Biomedical Engineering",
  "Bioinformatics",
  "Genetic Engineering",
  "Mining Engineering",
  "Metallurgical & Materials Engineering",
  "Marine Engineering & Naval Architecture",
  "Textile Engineering",
  "Food Technology & Processing",
  "Agricultural Engineering",

  // Architecture & Design
  "B.Arch (Architecture)",
  "Planning & Urban Design",
  "Interior Design",
  "Fashion & Textile Design",
  "Graphic & Visual Communication Design",
  "Animation, VFX & Gaming",
  "Fine Arts (BFA)",

  // Pharmacy & Healthcare
  "B.Pharmacy (Bachelor of Pharmacy)",
  "M.Pharmacy (Master of Pharmacy)",
  "Pharm.D (Doctor of Pharmacy)",
  "MBBS (Medicine & Surgery)",
  "BDS (Dental Surgery)",
  "BAMS (Ayurvedic Medicine)",
  "BHMS (Homeopathic Medicine)",
  "BUMS (Unani Medicine)",
  "BPT (Bachelor of Physiotherapy)",
  "B.Sc Nursing",
  "Medical Lab Technology (MLT)",
  "Radiology & Imaging Technology",
  "Optometry",
  "Veterinary Science (BVSc)",

  // Computer Applications & Pure Sciences
  "BCA (Bachelor of Computer Applications)",
  "MCA (Master of Computer Applications)",
  "B.Sc Computer Science",
  "B.Sc Information Technology",
  "B.Sc Data Science & Analytics",
  "B.Sc Mathematics",
  "B.Sc Statistics",
  "B.Sc Physics",
  "B.Sc Chemistry",
  "B.Sc Biotechnology",
  "B.Sc Agriculture",
  "B.Sc Horticulture",
  "B.Sc Forestry",
  "B.Sc Psychology",
  "B.Sc Food Science & Nutrition",

  // Commerce, Finance & Management
  "B.Com (General)",
  "B.Com (Honours)",
  "B.Com (Computers & IT)",
  "B.Com (Accounting & Finance)",
  "B.Com (Taxation)",
  "BBA (Bachelor of Business Administration)",
  "BBM (Bachelor of Business Management)",
  "MBA (Master of Business Administration)",
  "PGDM (Post Graduate Diploma in Management)",
  "Hospital & Healthcare Management",
  "Hotel & Hospitality Management",
  "Event Management",

  // Humanities, Social Sciences & Law
  "BA (English Literature)",
  "BA (Economics)",
  "BA (Political Science)",
  "BA (History)",
  "BA (Sociology)",
  "BA (Psychology)",
  "BA (Journalism & Mass Communication)",
  "Public Administration",
  "LLB (Bachelor of Law)",
  "BA LLB (Integrated Law)",
  "BBA LLB (Integrated Law)",
  "LLM (Master of Law)",

  // Vocational & Advanced Programs
  "Polytechnic / Diploma Engineering",
  "B.Ed (Bachelor of Education)",
  "M.Ed (Master of Education)",
  "M.Tech (Engineering Post-Graduation)",
  "M.Sc (Science Post-Graduation)",
  "MA (Arts Post-Graduation)",
  "PhD (Doctor of Philosophy)"
] as const;