export const CATEGORY_TEMPLATES: Record<string, string> = {
  "AI Event": `About the Event:\n\nWho Should Attend:`,
  "Alumni Event": `About the Event:\n\nWho Should Attend:`,
  "Auto & EV Expo": `About the Expo:\n\nWho Should Attend:`,
  "Awards Night": `About the Event:\n\nWho Should Attend:`,
  "Career Event": `About the Event:\n\nWho Should Attend:`,
  "Charity Event": `About the Initiative:\n\nWho Should Attend:`,
  "College Event": `About the Event:\n\nWho Should Attend:`,
  "College Fest": `About the Fest:\n\nWho Should Attend:`,
  "Comedy Show": `About the Show:\n\nWho Should Attend:`,
  "Community Event": `About the Gathering:\n\nWho Should Attend:`,
  "Concert": `About the Concert:\n\nWho Should Attend:`,
  "Conference": `About the Conference:\n\nWho Should Attend:`,
  "Creator Meetup": `About the Meetup:\n\nWho Should Attend:`,
  "Default Event": `About the Event:\n\nWho Should Attend:`,
  "Developer Event": `About the Event:\n\nWho Should Attend:`,
  "Educational Fair": `About the Fair:\n\nWho Should Attend:`,
  "Exhibition": `About the Exhibition:\n\nWho Should Attend:`,
  "Expo": `About the Expo:\n\nWho Should Attend:`,
  "Film Festival": `About the Festival:\n\nWho Should Attend:`,
  "Fitness Event": `About the Event:\n\nWho Should Attend:`,
  "Food Festival": `About the Festival:\n\nWho Should Attend:`,
  "Founder Meetup": `About the Meetup:\n\nWho Should Attend:`,
  "Gaming & Esports": `About the Tournament:\n\nWho Should Attend:`,
  "Hackathon": `About the Hackathon:\n\nWho Should Attend:`,
  "Investor Event": `About the Event:\n\nWho Should Attend:`,
  "Music Festival": `About the Festival:\n\nWho Should Attend:`,
  "Networking Event": `About the Event:\n\nWho Should Attend:`,
  "Open Mic": `About the Event:\n\nWho Should Attend:`,
  "Pet Event": `About the Event:\n\nWho Should Attend:`,
  "Running Event": `About the Event:\n\nWho Should Attend:`,
  "Sports Tournament": `About the Tournament:\n\nWho Should Attend:`,
  "Startup Event": `About the Event:\n\nWho Should Attend:`,
  "Summit": `About the Summit:\n\nWho Should Attend:`,
  "Tech Event": `About the Event:\n\nWho Should Attend:`,
  "Wellness Event": `About the Event:\n\nWho Should Attend:`,
  "Women Event": `About the Event:\n\nWho Should Attend:`,
  "Workshop": `About the Workshop:\n\nWho Should Attend:`
};

export const teamOptions = ["Solo", "Teams of 2-4", "Teams of 4+", "Both Solo & Team"];
