export const theme = {
  colors: {
    brand: '#6C47FF',
    brandHover: '#5535E0',
    brandLight: '#EEF0FF',
    brandDark: '#3A1DA0',
    background: '#F5F5F7',
    surface: '#FFFFFF',
    surfaceSecondary: '#F8F9FA',
    textPrimary: '#1D1D1F',
    textSecondary: '#86868B',
    textMuted: '#A1A1A6',
    border: '#E5E5EA',
    borderLight: '#F0F0F2',
    success: '#10B981',
    successBg: '#ECFDF5',
    warning: '#F59E0B',
    warningBg: '#FFFBEB',
    danger: '#EF4444',
    dangerBg: '#FEF2F2',
    darkCard: '#18181B',
  },
  typography: {
    fontFamily: {
      heading: 'Outfit-Bold',
      headingSemiBold: 'Outfit-SemiBold',
      headingMedium: 'Outfit-Medium',
      headingExtraBold: 'Outfit-ExtraBold',
      headingBlack: 'Outfit-Black',
      regular: 'Switzer-Regular',
      medium: 'Switzer-Medium',
      semiBold: 'Switzer-Semibold',
      bold: 'Switzer-Bold',
      black: 'Switzer-Extrabold',
    },
    fontSize: {
      xs: 11,
      sm: 13,
      base: 15,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      display: 30,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    brand: {
      shadowColor: '#6C47FF',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 6,
    },
  },
};

export const FONTS = {
  // Heading Fonts (Outfit)
  outfit: {
    regular: 'Outfit-Regular',
    medium: 'Outfit-Medium',
    semiBold: 'Outfit-SemiBold',
    bold: 'Outfit-Bold',
    extraBold: 'Outfit-ExtraBold',
    black: 'Outfit-Black',
  },
  // Body Fonts (Switzer)
  switzer: {
    regular: 'Switzer-Regular',
    medium: 'Switzer-Medium',
    semiBold: 'Switzer-Semibold',
    bold: 'Switzer-Bold',
    extraBold: 'Switzer-Extrabold',
  },
  // Quick Aliases
  heading: 'Outfit-Bold',
  headingSemiBold: 'Outfit-SemiBold',
  headingMedium: 'Outfit-Medium',
  headingExtraBold: 'Outfit-ExtraBold',
  body: 'Switzer-Regular',
  bodyMedium: 'Switzer-Medium',
  bodySemiBold: 'Switzer-Semibold',
  bodyBold: 'Switzer-Bold',
};